export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const HANDLE_QUANTITY_REQUEST = "HANDLE_QUANTITY_REQUEST";
export const HANDLE_QUANTITY_SUCCESS = "HANDLE_QUANTITY_SUCCESS";
export const HANDLE_QUANTITY_FAILURE = "HANDLE_QUANTITY_FAILURE";

export const HOMEPAGE_DATA_SUCCESS = "HOMEPAGE_DATA_SUCCESS";
